title: Testing Blog Site
author: GitHub Course 3
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
Following Course 3 instructions to create GitHub Page!

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
